version: '3.8'
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - backend

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: myssix_db
      POSTGRES_USER: myssix
      POSTGRES_PASSWORD: test12
    volumes:
      - ./db/data:/var/lib/postgresql/data # map data INSIDE of the container to dir ./db/data
    ports:
      - "5400:5432"

  crawler:
    build: ./crawler
    image: crawler:latest # my own name for the image
    container_name: crawler
    environment:
      # argument to the crawler
      HOST: iotdev.snu.ac.kr
      PORT: 58132
      # argument to connect to db
      DB_HOST: db
      DB_NAME: myssix_db
      DB_PORT: 5432
      DB_USER: myssix
      DB_PASS: test12
    restart: unless-stopped
    depends_on:
      - db

  backend:
    build: ./backend
    image: backend:latest
    container_name: backend
    environment:
      # argument to connect to db
      DB_HOST: db
      DB_NAME: myssix_db
      DB_PORT: 5432
      DB_USER: myssix
      DB_PASS: test12
    restart: unless-stopped
    depends_on:
      - db

  client:
    build: ./client
    image: client:latest
    container_name: client
    depends_on:
      - backend